name: FlightControl
main: org.spazzinq.flightcontrol.FlightControl
version: ${revision}
api-version: "1.13"
author: Spazzinq
description: "An elegant solution for controlling player flight"
load: POSTWORLD
softdepend: [Essentials, Lands, MVdWPlaceholderAPI, WorldEdit, WorldGuard]

commands:
  flightcontrol:
    description: FlightControl administration
    aliases: [fc]
  toggletrail:
    description: Per-player trail toggle
    aliases: [trail, tt, trailtoggle]
  tempfly:
    description: Gives temporary flight
    aliases: [tfly, tempflight, silenttempfly, flytime]
  flyspeed:
    description: Sets flight speed
    aliases: [flightspeed]


permissions:
  flightcontrol.towny:
    description: Enables flight in player's own town
    default: false
    children:
      own: true
  flightcontrol.lands:
    description: Enables flight in player's own land
    default: false
    children:
      own: true
      trusted: false
  flightcontrol.claim:
    description: Enables flight in player's own claim
    default: false
    children:
      own: true
      trusted: false
  flightcontrol.flyall:
    description: Ability to automatically fly in all regions that are not disabled
    default: false
  flightcontrol.flycommand:
    description: Ability to use the fly command (granted by default)
    default: true
  flightcontrol.flyspeed:
    description: Ability to set flight speed
    default: op
    children:
      others: true
  flightcontrol.tempfly:
    description: Ability to give temporary flight
    default: op
    children:
      others: true
  flightcontrol.ignore:
    description: Ignores FlightControl's checks and does not change flight
    default: false
  flightcontrol.nearbypass:
    description: Bypasses the "nearby_disable" check
    default: op
  flightcontrol.bypass:
    description: Bypasses all fly restrictions and always allows flight
    default: op
  flightcontrol.admin:
    description: Ability to use FlightControl administrative commands (automatically given to OPs)
    default: op