name: CI
on:
  # Trigger the workflow on push or pull request,
  # but only for the master & beta branches
  push:
    branches:
      - master
      - beta
  pull_request:
    branches:
      - master
      - beta
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'gradle'
    - run: ./gradlew clean shadowJar --no-daemon
    - uses: actions/upload-artifact@v3
      with:
        name: FlightControl-build
        path: FlightControl/build/libs/FlightControl.jar